Repository tagesspiegel/terraform-argocd-application-set, pull requests merged in 2023-10, with the labels that each got.

#5 feat: added possibility to add an application name suffix
  README.md
  main.tf
  variables.tf
Labels: feature, size/S

#6 fix: go template in go template syntax
  examples/.terraform.lock.hcl
  examples/main.tf
  main.tf
Labels: fix, size/M

#7 feat: TPLAT-287 added feature to ignore differences in spec
  README.md
  main.tf
  variables.tf
Labels: feature, size/S

#8 feat: environment context based annotations
  README.md
  examples/main.tf
  main.tf
  variables.tf
Labels: feature, size/S

#10 fix: application name suffix not null value
  examples/.terraform.lock.hcl
  examples/main.tf
  main.tf
Labels: fix, size/S

#11 chore: updated and formatted github actions
  .github/workflows/check_tf_docs.yaml
  .github/workflows/generate_tf_docs.yaml
  .github/workflows/pull_request_labels.yaml
  .github/workflows/tests.yaml
Labels: chore, size/XS
